name: test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v3
        with:
          go-version: 1.15
      - run: go test -v ./...
      - run: echo "${{ secrets.APP_PRIVATE_KEY }}" > /tmp/APP_PRIVATE_KEY.pem
      - run: go run ./example
        env:
          GITHUB_APP_ID: ${{ secrets.APP_ID }}
          GITHUB_APP_INSTALLATION_ID: ${{ secrets.APP_INSTALLATION_ID }}
          GITHUB_APP_PRIVATE_KEY_NAME: /tmp/APP_PRIVATE_KEY.pem

  golangci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: golangci/golangci-lint-action@v2
        with:
          version: v1.36
